name = "pluto-speaker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# 开启 nodejs 兼容模式，因为我们使用了 Buffer
compatibility_flags = [ "nodejs_compat" ]

[vars]
  SUPABASE_URL = "https://unqlcenxiolnuguneznl.supabase.co"
  SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVucWxjZW54aW9sbnVndW5lem5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzA5MTMwMjksImV4cCI6MjA0NjQ4OTAyOX0.UA88XQMd10VyFwkG5jDgED0wnn5z9rmjobx8nv4voGo"
  JWT_SECRET = "WA7stV/cayvoSisg0Y4NUVUzR+JftcfNEmAxilY4dCt1IZvMJoWoK+nvDOzI5z1sI4gdPiun2lfOszX9IoiCPw=="
  OPENAI_API_KEY = "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"

# 如果你想在生产环境使用不同的环境变量，可以这样设置：
[env.production]
  vars = { }  # 生产环境的环境变量

[env.staging]
  vars = { }  # 测试环境的环境变量